services:
  app:
    container_name: golang
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./public:/app/public
    restart: unless-stopped
    depends_on:
      - python-server
    networks:
      - my_network

  python-server:
    container_name: python
    build:
      context: python-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network: